events {
  worker_connections 1024;
}

http {
  # Docker embedded DNS — resolves container names dynamically
  resolver 127.0.0.11 valid=10s;

  server {
    listen 80;

    location = /_auth {
      internal;
      set $auth_upstream http://microservice-auth-service-app:3001/validate;
      proxy_pass         $auth_upstream;
      proxy_pass_request_body off;
      proxy_set_header   Content-Length    "";
      proxy_set_header X-Original-URI $request_uri;
    }

    # microservice-auth-service: public endpoints (login, register, refresh — no JWT guard needed)
    location /auth/ {
      set $auth_upstream http://microservice-auth-service-app:3001;
      rewrite ^/auth/(.*)$ /$1 break; 
      proxy_pass         $auth_upstream;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # microservice-users-service: protected endpoints
    # JWT validation should be added here (e.g. via auth_request or OpenResty/lua).
    # Once validated, inject identity headers so services never re-validate tokens.
    location /users/ {
      auth_request /_auth;
      auth_request_set $user_id $upstream_http_x_user_id;
      auth_request_set $user_roles $upstream_http_x_user_roles;


      set $users_upstream http://microservice-users-service-app:3002;
      rewrite ^/users/(.*)$ /$1 break;
      proxy_pass         $users_upstream;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-User-Id         $user_id;
      proxy_set_header X-User-Roles       $user_roles;
    }
  }
}
